kind: Deployment
apiVersion: apps/v1
metadata:
  name: admin-console-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: admin-console-operator
  template:
    metadata:
      labels:
        name: admin-console-operator
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: admin-console-operator
          command:
            - admin-console-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: admin-console-operator
            - name: PLATFORM_TYPE
              value: openshift
          securityContext:
            allowPrivilegeEscalation: false
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'epamedp/admin-console-operator:v2.5.1'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: {{ .Values.name }}
      serviceAccount: {{ .Values.name }}
      securityContext:
        runAsNonRoot: true
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600